config/routes.rb
Rails.application.routes.draw do
  root "tops#index"
  # root "graphs#index"
  devise_for :users, controllers: {
                       registrations: "users/registrations",
                       passwords: "users/passwords",
                     }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tops
  get "/graphs", to: "graphs#index"
  # post "/graphs", to: "graphs#create"
  # patch "/graphs", to: "graphs#update"
  resource :graphs, only: [:index, :create, :update]
  resources :cigar_infos
  resources :profiles
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates :box_price, presence: true, numericality: { only_integer: true }
  validates :cigar_amount, presence: true, numericality: { only_integer: true }
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # 格アクションで共通の処理をset_profileで定義しbefore_actionで呼び出す
  before_action :set_profile, only: %i[edit update destroy]

  def index
    @profile = current_user.profiles.last
    if @profile.nil?
    else
      total_actual_cigarettes = current_user.graphs.all.sum(:cigarette)
      profile = current_user.profiles.first
      total_ordinary_cigarettes = current_user.graphs.count*profile.cigar_amount
      @total_saved_cigarettes = total_ordinary_cigarettes-total_actual_cigarettes
      @total_saved_money = (total_ordinary_cigarettes-total_actual_cigarettes)*profile.box_price/NUMBER_OF_CIGARETTES_IN_A_BOX
      @total_prolonged_life = (total_ordinary_cigarettes-total_actual_cigarettes)*PROLONGED_MINUTES_PER_ONE_CIGARETTE
      @days = (@total_prolonged_life/1440).to_i
      @hours = (@total_prolonged_life%1440/60).to_i
      @minutes = (@total_prolonged_life%1440%60).to_i
    end
  end

  def new
    @profile = current_user.profiles.new
  end

  def create
    @profile = current_user.profiles.new(profile_params)
    if @profile.save
      redirect_to profiles_path, notice: "登録しました"
    else
      flash.now[:alert] = "登録に失敗しました"
      render :new
    end
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to profiles_path, notice: "更新しました"
    else
      flash.now[:alert] = "更新に失敗しました"
      render :edit
    end
  end

  def destroy
    @profile.destroy!
    redirect_to profiles_path, alert: "削除しました"
  end

  private

  def profile_params
    params.require(:profile).permit(:cigar_amount, :box_price)
  end

  def set_profile
    @profile = current_user.profiles.find(params[:id])
  end
end

app/views/profiles/_form.html.erb
<%= render "layouts/error_messages2" %>
<%= form_with model: @profile, local: true do |form| %>
  <div class="form-group">
    <%= form.label :box_price %>
    <%= form.text_field :box_price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :cigar_amount %>
    <%= form.text_field :cigar_amount, class: "form-control" %>
  </div>
  <div>
    <%= form.submit button_value, class: "btn btn-primary btn-block" %>
  </div>
  <br>
  <div>
    <%= link_to :back do %>
      <button class="btn btn-danger btn-block">戻る</button>
    <% end %> 
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h2 class="text-center">プロフィール編集</h2>
<%= render "form", button_value: "更新" %>

app/views/profiles/index.html.erb
<h2 class="text-center">プロフィール</h2>
<br>
<% if @profile.present? %>
  <ul class="frame">
    <li class="list"><i class="fas fa-dollar-sign"></i> 現在吸っているタバコは一箱<%= @profile.box_price %>円</li>
    <li class="list"><i class="fas fa-smoking"></i> 普段の喫煙本数は1日に<%= @profile.cigar_amount %>本</li>
    <li class="list"><i class="fas fa-smoking-ban"></i> 今までに我慢したタバコ : <span class="font"><%= @total_saved_cigarettes %>本</span></li>
    <li class="list"><i class="fas fa-coins"></i> 今までに節約した金額 : <span class="font"><%= @total_saved_money %>円</span></li>
    <li class="list"><i class="far fa-heart"></i> 延びた寿命 : <span class="font"><%= @days %>日<%= @hours %>時間<%= @minutes %>分</span></li>
  </ul>
  
  <br>
  <div class="text-center">
    <td>
      <%= link_to 'プロフィールを編集', edit_profile_path(@profile), class: " btn-edit" %>
    </td>
    <td>
      <%= link_to 'プロフィールを削除', @profile, method: :delete, data: { confirm: "削除しますか?" }, class: "btn-delete" %>
    </td>
  </div>
<% else %>
  <ul class="frame">
    <li class="list">現在吸っているタバコの値段と普段の喫煙本数を登録しましょう。我慢したタバコ、節約額、伸びた寿命が算出されます。</li>
  </ul>
  <br>
  <div class="text-center">
    <%= link_to 'プロフィールを登録', new_profile_path, class: "btn-create" %>
  </div>
<% end %>

app/views/profiles/new.html.erb
<h2 class="text-center">プロフィール登録</h2>
<%= render "form", button_value: "登録" %>