config/routes.rb
Rails.application.routes.draw do
  root "tops#index"
  # root "graphs#index"
  devise_for :users, controllers: {
                       registrations: "users/registrations",
                       passwords: "users/passwords",
                     }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tops
  get "/graphs", to: "graphs#index"
  # post "/graphs", to: "graphs#create"
  # patch "/graphs", to: "graphs#update"
  resource :graphs, only: [:index, :create, :update]
  resources :cigar_infos
  resources :profiles
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
end

app/views/shared/_flash_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name %>" role="alert" id="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header class="sticky-top">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <% if user_signed_in? %>
      <%= link_to "タバコマネージャー", graphs_path, class: 'navbar-brand' %>
    <% else %>
      <%= link_to "タバコマネージャー", tops_path, class: 'navbar-brand' %>
    <% end %>
    
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="ナビゲーションの切替">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to graphs_path, class: 'nav-link' do %>
              <i class="far fa-chart-bar"></i> 減煙記録
            <% end %>
          </li>
          <li class="nav-item active">
            <%= link_to profiles_path, class: 'nav-link' do %>
              <i class="far fa-user"></i> プロフィール
            <% end %>
          </li>
          <li class="nav-item active">
            <%= link_to cigar_infos_path, class: 'nav-link' do %>
              <i class="fas fa-book"></i> コレクション
            <% end %>
          </li>
          
          <li class="nav-item active">
            <%= link_to edit_user_registration_path, class: 'nav-link' do %>
              <i class="far fa-edit"></i> アカウント編集
            <% end %>
          </li>
          <li class="nav-item active">
            <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link' do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
            <% end %>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= link_to new_user_registration_path, class: 'nav-link' do %>
               <i class="far fa-user-circle"></i> アカウント登録
            <% end %>
          </li>
          <li class="nav-item active">
            <%= link_to new_user_session_path, class: 'nav-link' do %>
              <i class="fas fa-sign-in-alt"></i> ログイン
            <% end %>
          </li>
          <li class="nav-item active">
            <%= link_to users_guest_sign_in_path, method: :post, class: 'nav-link' do %>
              <i class="far fa-eye"></i> ゲストログイン
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>