config/routes.rb
Rails.application.routes.draw do
  root "tops#index"
  # root "graphs#index"
  devise_for :users, controllers: {
                       registrations: "users/registrations",
                       passwords: "users/passwords",
                     }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tops
  get "/graphs", to: "graphs#index"
  # post "/graphs", to: "graphs#create"
  # patch "/graphs", to: "graphs#update"
  resource :graphs, only: [:index, :create, :update]
  resources :cigar_infos
  resources :profiles
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
end

app/models/cigar_info.rb
class CigarInfo < ApplicationRecord
  belongs_to :user
  # validates :img, presence: true
  validate :img_size
  validates :brand, presence: true, length: { maximum: 50 }
  validates :price, presence: true, numericality: { only_integer: true }
  validates :text, length: { maximum: 200 }

  mount_uploader :img, ImgUploader

  private
  # 最新のスマホに対応した画像サイズ
  def img_size
    if img.size > 5.megabyte
      errors.add(:img, "が5MB以上です")
    end
  end

end

app/controllers/cigar_infos_controller.rb
class CigarInfosController < ApplicationController
  # 格アクションで共通の処理をset_cigarinfoで定義しbefore_actionで呼び出す
  before_action :set_cigarinfo, only: [:show, :edit, :update, :destroy]

  def index
    @cigarinfos = current_user.cigar_infos.order(id: :asc)
  end

  def show
  end

  def new
    @cigarinfo = current_user.cigar_infos.new
  end

  def create
    @cigarinfo = current_user.cigar_infos.new(cigarinfo_params)
    if @cigarinfo.save
      redirect_to cigar_info_path(@cigarinfo), notice: "登録しました" #createアクションで定義した変数@cigarinfo
    else
      flash.now[:alert] = "登録に失敗しました"
      render :new
    end
  end

  def edit
  end

  def update
    if @cigarinfo.update(cigarinfo_params)
      redirect_to @cigarinfo, notice: "更新しました"
    else
      flash.now[:alert] = "更新に失敗しました"
      render :edit
    end
  end

  def destroy
    @cigarinfo.destroy!
    redirect_to cigar_infos_path, alert: "削除しました"
  end

  private

  def set_cigarinfo
    @cigarinfo = current_user.cigar_infos.find(params[:id])
  end

  def cigarinfo_params
    params.require(:cigar_info).permit(:brand, :price, :text, :img, :remove_img)
  end

end

app/views/cigar_infos/_form.html.erb
<%= render "layouts/error_messages" %>
<%= form_with model: @cigarinfo, local: true do |form| %>
  <div class="form-group">
    <%= form.label :img %>
    <%= form.file_field :img, class: "form-control" %>
    <p><%= form.check_box :remove_img %>画像を削除</p>
  </div>
  <div class="form-group">
    <%= form.label :brand %>
    <%= form.text_field :brand, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :text %>
    <%= form.text_area :text, class: "form-control", rows: 10 %>
  </div>
  <div>
    <%= form.submit button_value, class: "btn btn-primary btn-block" %>
  </div>
  <br>
  <div>
    <%= link_to :back do %>
      <button class="btn btn-danger btn-block">戻る</button>
    <% end %> 
  </div>
<% end %>

app/views/cigar_infos/edit.html.erb
<h2 class="text-center">タバコ情報編集</h2>
<%= render "form", button_value: "更新" %>

app/views/cigar_infos/index.html.erb
<h2 class="text-center">コレクション</h2>
<% if @cigarinfos.present? %>
  <table class="table table-borderd table-striped mt-4">
    <thead class="table-primary">
      <tr>
        <th scope="col"></th>
        <th scope="col" class="w-50">タバコ銘柄</th>
        <th scope="col" class="w-40">価格</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @cigarinfos.each.with_index(1) do |cigarinfo, i| %>
        <tr>
          <td scope="row" class="text-center"><%= image_tag cigarinfo.img.url, class:'icon' if cigarinfo.img? %></td>
          <td class="break-word"><%= link_to cigarinfo.brand, cigarinfo %></td>
          <td class="break-word"><%= cigarinfo.price %>円</td>
          <td class="text-center">
            <%= link_to cigarinfo, method: :delete, data: { confirm: "削除しますか?" } do %>
              <i class="far fa-trash-alt trash"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
<br>
  <ul class="frame">
    <li class="list">吸ったタバコのレビューをしましょう。</li>
  </ul>
<% end %>
<br>
<div class="text-center">
  <%= link_to 'コレクションを登録', new_cigar_info_path, class: "btn-create" %>
</div>

app/views/cigar_infos/new.html.erb
<h2 class="text-center">タバコ情報登録</h2>
<%= render "form", button_value: "登録" %>

app/views/cigar_infos/show.html.erb
<h2 class="text-center">タバコ情報</h2>
<section class="card border-dark mt-5">
  <div class="text-center card-header">
    <h4><%= @cigarinfo.brand %></h4>
  </div>
  <div class="card-body">
    <td>
      <p><%= image_tag @cigarinfo.img.url, class:'pic' if @cigarinfo.img? %></p>
      <h5><%= @cigarinfo.price %>円</h5>
    </td>
    <td><%= simple_format(@cigarinfo.text) %></td>
    <%# < class="card-text"><%= simple_format(h @cigarinfo.text)%>
  </div>
</section>

<br>
<div class="text-center">
  <td>
    <%= link_to 'タバコ情報を編集', edit_cigar_info_path, class: " btn-edit" %>
  </td>
  <td>
    <%= link_to 'コレクションに戻る', cigar_infos_path, class: "btn-delete" %>
  </td>
</div>